spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.30/dbsell?characterEncoding=utf-8&userSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  freemarker:
    charset: utf-8
    suffix: .ftl
    content-type: text/html; charset=utf-8
    template-loader-path: classpath:/templates
  messages:
    basename: i18n/messages
    encoding: UTF-8
  http:
      encoding:
        charset: utf-8
        force: true
        enabled: true
server:
  context-path: /sell